services:
  audioseal:
    build:
      context: .
      dockerfile: src/plugins/models/audio_seal/Dockerfile
    ports:
      - "${AUDIOSEAL_PORT}:${AUDIOSEAL_PORT}" # Reads from .env
    environment:
      - APP_PORT=${AUDIOSEAL_PORT} # Injects into container

  silentcipher:
    build:
      context: .
      dockerfile: src/plugins/models/silent_cipher/Dockerfile
    ports:
      - "${SILENTCIPHER_PORT}:${SILENTCIPHER_PORT}"
    environment:
      - APP_PORT=${SILENTCIPHER_PORT}

  wavmark:
    build:
      context: .
      dockerfile: src/plugins/models/wavmark/Dockerfile
    ports:
      - "${WAVMARK_PORT}:${WAVMARK_PORT}"
    environment:
      - APP_PORT=${WAVMARK_PORT}

  vae:
    build:
      context: .
      dockerfile: src/plugins/attacks/vae/Dockerfile
    ports:
      - "${VAE_PORT}:${VAE_PORT}"
    environment:
      - APP_PORT=${VAE_PORT}

  diffusion:
    build:
      context: .
      dockerfile: src/plugins/attacks/diffusion/Dockerfile
    ports:
      - "${DIFFUSION_PORT}:${DIFFUSION_PORT}"
    environment:
      - APP_PORT=${DIFFUSION_PORT}

  speech_tokenization:
    build:
      context: .
      dockerfile: src/plugins/attacks/speech_tokenization/Dockerfile
    ports:
      - "${SPEECH_TOKENIZATION_PORT}:${SPEECH_TOKENIZATION_PORT}"
    environment:
      - APP_PORT=${SPEECH_TOKENIZATION_PORT}

  neural_vocoder:
    build:
      context: .
      dockerfile: src/plugins/attacks/neural_vocoder/Dockerfile
    ports:
      - "${NEURAL_VOCODER_PORT}:${NEURAL_VOCODER_PORT}"
    environment:
      - APP_PORT=${NEURAL_VOCODER_PORT}

  speech_enhancement:
    build:
      context: .
      dockerfile: src/plugins/attacks/speech_enhancement/Dockerfile
    ports:
      - "${SPEECH_ENHANCEMENT_PORT}:${SPEECH_ENHANCEMENT_PORT}"
    environment:
      - APP_PORT=${SPEECH_ENHANCEMENT_PORT}
  
  timbrewm:
    build:
      context: .
      dockerfile: src/plugins/models/timbrewm/Dockerfile
    ports:
      - "${TIMBREWM_PORT}:${TIMBREWM_PORT}"
    environment:
      - APP_PORT=${TIMBREWM_PORT}
